replicaCount: 1
image:
  repository: sumairjaved/my-frontend
  imagePullPolicy: Always
  tag: "dd19ef683c7557a94fd62216ac152a515e7ef305"
service:
  type: NodePort # or ClusterIP if only internal
  port: 5000 # Service port
  targetPort: 5000 # Container port
  nodePort: 30080 # Optional: set specific NodePort
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  name: ""
httpRoute:
  enabled: false
ingress:
  enabled: false # Disable ingress completely
