name: Build and Push Docker Image (Hardcoded Credentials)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub (Hardcoded)
        run: echo "dckr_pat_R27eOnC_PVjhaT7eBNHEMoYe6yY" | docker login -u sumairjaved --password-stdin

      - name: Build Docker image
        run: docker build -t sumairjaved/my-frontend:latest .

      - name: Push Docker image
        run: docker push sumairjaved/my-frontend:latest
